#!/usr/bin/python

import MySQLdb

# Open database connection
db = MySQLdb.connect("localhost","testuser","test123","TESTDB" )

# prepare a cursor object using cursor() method
cursor = db.cursor()
cursor.execute("DROP TABLE IF EXISTS User")

# Create table as per requirement
sql = """CREATE TABLE User (
         Interestid CHAR(20) NOT NULL,
         InterestnAme CHAR(20) NOT NULL,
         Userid CHAR(20) NOT NULL,
          )"""

cursor.execute(sql)

# disconnect from server
db.close()
